---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Arc Tavern"
keywords:    "arc, tavern, miami, arcade, beer, bar, drink, drinking, adult, gaming, fun"
description: "Arc Tavern"
source_link: "chalvar.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#295ba7'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  firebrick: '#b22222'
  purple2:   '#7f00ff'
  teal:      '#04aba0'
  darkblue:  '#3d5786'
  pink:      '#eb6782'
  yellow:    '#d7c82b'


kramdown:
  auto_ids:  false
comments: true

